Add support for Debian 13 and update recommended PHP and MariaDB versions

diff --git a/idoit-install b/idoit-install
--- a/idoit-install
+++ b/idoit-install
@@ -3,9 +3,7 @@
 ##
 ## Install i-doit on a GNU/Linux operating system
 ##
-
-##
-## Copyright (C) 2017-22 synetics GmbH, <https://i-doit.com/>
+## Copyright (C) 2017-26 i-doit GmbH, <https://i-doit.com/>
 ##
 ## This program is free software: you can redistribute it and/or modify
 ## it under the terms of the GNU Affero General Public License as published by
@@ -52,8 +50,8 @@ IFS=$'\n\t'
 : "${JOBS_BIN:="/usr/local/bin/idoit-jobs"}"
 : "${CRON_FILE:="/etc/cron.d/i-doit"}"
 : "${BACKUP_DIR:="/var/backups/i-doit"}"
-: "${RECOMMENDED_PHP_VERSION:="8.2"}"
-: "${RECOMMENDED_MARIADB_VERSION:="10.6"}"
+: "${RECOMMENDED_PHP_VERSION:="8.4"}"
+: "${RECOMMENDED_MARIADB_VERSION:="10.11"}"
 
 ##
 ## Runtime settings
@@ -276,9 +274,9 @@ function identifyOS {
         MARIADB_UNIT="mariadb"
         MEMCACHED_UNIT="memcached"
         PHP_FPM_UNIT="php-fpm"
+
     elif [[ "$NAME" == "CentOS Linux" && "$VERSION_ID" == "8" ]]; then
         abort "Warning: This OS is not officially supported by i-doit"
-
         OS="centos8"
         APACHE_USER="apache"
         APACHE_GROUP="apache"
@@ -291,9 +289,25 @@ function identifyOS {
         MARIADB_UNIT="mariadb"
         MEMCACHED_UNIT="memcached"
         PHP_FPM_UNIT="php-fpm"
-    elif [[ "$NAME" == "Debian GNU/Linux" && "$VERSION" == "12 (bookworm)" ]]; then
+
+    elif [[ "$NAME" == "Debian GNU/Linux" && "$VERSION" == "13 (trixie)" ]]; then
         export DEBIAN_FRONTEND="noninteractive"
 
+        OS="debian13"
+        APACHE_USER="www-data"
+        APACHE_GROUP="www-data"
+        APACHE_CONFIG_FILE="/etc/apache2/sites-available/i-doit.conf"
+        MARIADB_CONFIG_FILE="/etc/mysql/mariadb.conf.d/99-i-doit.cnf"
+        PHP_CONFIG_FILE="/etc/php/8.4/mods-available/i-doit.ini"
+        MARIADB_SOCKET="/var/run/mysqld/mysqld.sock"
+        PHP_FPM_SOCKET="/var/run/php/php8.4-fpm.sock"
+        APACHE_UNIT="apache2"
+        MARIADB_UNIT="mysql"
+        MEMCACHED_UNIT="memcached"
+        PHP_FPM_UNIT="php8.4-fpm"
+
+    elif [[ "$NAME" == "Debian GNU/Linux" && "$VERSION" == "12 (bookworm)" ]]; then
+        export DEBIAN_FRONTEND="noninteractive"
         OS="debian12"
         APACHE_USER="www-data"
         APACHE_GROUP="www-data"
@@ -306,6 +320,7 @@ function identifyOS {
         MARIADB_UNIT="mysql"
         MEMCACHED_UNIT="memcached"
         PHP_FPM_UNIT="php8.2-fpm"
+
     elif [[ "$NAME" == "Debian GNU/Linux" && "$VERSION" == "11 (bullseye)" ]]; then
         export DEBIAN_FRONTEND="noninteractive"
         abort "Error: Debian 11 is out-dated. It's not supported anymore. Please upgrade."
@@ -577,6 +592,9 @@ function checkSoftwareRequirements {
 
 function configureOS {
     case "$OS" in
+    "debian13")
+        configureDebian13
+        ;;
     "debian12")
         configureDebian12
         ;;
@@ -618,6 +636,26 @@ function configureOS {
         ;;
     esac
 }
+
+# Debian13
+function configureDebian13 {
+    log "Keep your Debian packages up-to-date"
+    apt-get -qq --yes update || abort "Unable to update Debian package repositories"
+    apt-get -qq --yes full-upgrade || abort "Unable to perform update of Debian packages"
+    apt-get -qq --yes clean || abort "Unable to cleanup Debian packages"
+    apt-get -qq --yes autoremove || abort "Unable to remove unnecessary Debian packages"
+
+    log "Install required Debian 12 packages"
+    apt-get -qq --yes install --no-install-recommends \
+        apache2 libapache2-mod-fcgid \
+        mariadb-client mariadb-server \
+        php-bcmath php-cli php-common php-curl php-fpm php-gd \
+        php-ldap php-mbstring php-mysql php-opcache php-pgsql \
+        php-soap php-xml php-zip \
+        php-memcached \
+        memcached unzip sudo moreutils || abort "Unable to install required Debian packages"
+}
+
 function configureDebian12 {
     log "Keep your Debian packages up-to-date"
     apt-get -qq --yes update || abort "Unable to update Debian package repositories"
@@ -1167,22 +1205,16 @@ function configurePHP {
     php_version=$(php --version | head -n1 -c7 | tail -c3)
 
     case "$php_version" in
-    "5.4" | "5.5" | "5.6" | "7.0" | "7.1" | "7.2" | "7.3")
+    "5.4" | "5.5" | "5.6" | "7.0" | "7.1" | "7.2" | "7.3" | "7.4" | "8.0"| "8.1")
         abort "PHP ${php_version} is way too old. Please upgrade. We recommend version ${RECOMMENDED_PHP_VERSION}."
-        ;;
-    "7.4")
-        abort "PHP ${php_version} is way too old. Please upgrade. We recommend version ${RECOMMENDED_PHP_VERSION}."
-        ;;
-    "8.0")
-        php_en_mod=$(command -v phpenmod)
-        ;;
-    "8.1")
-        php_en_mod=$(command -v phpenmod)
         ;;
     "8.2")
         php_en_mod=$(command -v phpenmod)
         ;;
     "8.3")
+        php_en_mod=$(command -v phpenmod)
+        ;;
+    "8.4")
         php_en_mod=$(command -v phpenmod)
         ;;
     *)
@@ -1231,7 +1263,7 @@ function configurePHPFPM {
     log "Configure PHP-FPM"
 
     case "$OS" in
-    "debian11" | "debian12" | "ubuntu2004" | "ubuntu2204" | "ubuntu2404")
+    "debian11" | "debian12" | "debian13" | "ubuntu2004" | "ubuntu2204" | "ubuntu2404")
         unitctl "restart" "$PHP_FPM_UNIT"
         ;;
     "rhel7" | "rhel8" | "rhel9" | "centos7" | "centos8")
@@ -1385,7 +1417,7 @@ EOF
 
         unitctl "restart" "$APACHE_UNIT"
         ;;
-    "debian11" | "debian12" | "ubuntu2004" | "ubuntu2204" | "ubuntu2404")
+    "debian11" | "debian12" | "debian13" | "ubuntu2004" | "ubuntu2204" | "ubuntu2404")
         a2_en_site=$(command -v a2ensite)
         a2_dis_site=$(command -v a2dissite)
         a2_en_mod=$(command -v a2enmod)
@@ -1495,11 +1527,19 @@ function configureMariaDB {
         MARIADB_HOSTNAME="$answer"
     fi
 
-    secureMariaDB
-
     # Check mariadb version
     local mariadb_version=""
-    mariadb_version=$(mysql --version | head -n1 | sed -e 's/.* Distrib \([0-9]*\.[0-9]*\)\.[0-9]*.*/\1/')
+
+    if [[ "$OS" == "debian13" ]]; then
+        # Debian 13 has MariaDB 10.11, but it is not possible to get the version number with the default method
+        # So we have to use a workaround to get the major and minor version number
+        mariadb_version=$(mysql --version | head -n1 | sed -e 's/.*from \([0-9]*\.[0-9]*\).*/\1/')
+    else
+        # For all other OSes we can get the major and minor version number with the default mysql client
+        mariadb_version=$(mysql --version | head -n1 | sed -e 's/.* Distrib \([0-9]*\.[0-9]*\).*/\1/')
+    fi
+
+    secureMariaDB
 
     log "Prepare shutdown of MariaDB"
     "$MARIADB_BIN" \
@@ -1517,12 +1557,8 @@ function configureMariaDB {
         MARIADB_INNODB_BUFFER_POOL_SIZE="$answer"
     fi
 
-    if [[ "$mariadb_version" != "10.11" ]]; then
-        log "Move old MariaDB log files"
-        mv /var/lib/mysql/ib_logfile[01] "$TMP_DIR" || abort "Unable to remove old log files"
-
-        log "Configure MariaDB settings"
-        cat <<EOF >"$MARIADB_CONFIG_FILE" || abort "Unable to create and edit file '${MARIADB_CONFIG_FILE}'"
+    log "Configure MariaDB settings"
+    cat <<EOF >"$MARIADB_CONFIG_FILE" || abort "Unable to create and edit file '${MARIADB_CONFIG_FILE}'"
 [mysqld]
 
 # This is the number 1 setting to look at for any performance optimization
@@ -1560,41 +1596,6 @@ innodb_stats_on_metadata = 0
 sql-mode = ""
 EOF
 
-    else
-        cat <<EOF >"$MARIADB_CONFIG_FILE" || abort "Unable to create and edit file '${MARIADB_CONFIG_FILE}'"
-[mysqld]
-# This is the number 1 setting to look at for any performance optimization
-# It is where the data and indexes are cached: having it as large as possible will
-# ensure MySQL uses memory and not disks for most read operations.
-# See https://mariadb.com/kb/en/innodb-buffer-pool/
-# Typical values are 1G (1-2GB RAM), 5-6G (8GB RAM), 20-25G (32GB RAM), 100-120G (128GB RAM).
-innodb_buffer_pool_size = 1G
-# Redo log file size, the higher the better.
-# MySQL/MariaDB writes one of these log files in a default installation.
-innodb_log_file_size = 512M
-innodb_sort_buffer_size = 64M
-sort_buffer_size = 262144 # default
-join_buffer_size = 262144 # default
-max_allowed_packet = 128M
-max_heap_table_size = 32M
-query_cache_min_res_unit = 4096
-query_cache_type = 1
-query_cache_limit = 5M
-query_cache_size = 80M
-tmp_table_size = 32M
-max_connections = 200
-innodb_file_per_table = 1
-# Disable this (= 0) if you have slow hard disks
-innodb_flush_log_at_trx_commit = 1
-innodb_flush_method = O_DIRECT
-innodb_lru_scan_depth = 2048
-table_definition_cache = 1024
-table_open_cache = 2048
-innodb_stats_on_metadata = 0
-sql-mode = ""
-EOF
-    fi
-
     if [[ -d "/var/log/mysql" ]]; then
         log "Let every user read the logs"
         chmod 755 /var/log/mysql
@@ -1606,9 +1607,6 @@ unitctl "start" "$MARIADB_UNIT"
 }
 
 function secureMariaDB {
-
-    local mariadb_version=""
-    mariadb_version=$(mysql --version | head -n1 | sed -e 's/.* Distrib \([0-9]*\.[0-9]*\)\.[0-9]*.*/\1/')
 
     echo -n -e \
         "Please enter a new password for MariaDB's super user '${MARIADB_SUPERUSER_USERNAME}' [leave empty for '${MARIADB_SUPERUSER_PASSWORD}']: "
@@ -1622,7 +1620,7 @@ function secureMariaDB {
     log "Set $MARIADB_SUPERUSER_USERNAME password and plugin 'mysql_native_password'"
     case "$mariadb_version" in
 
-    "10.11")
+    "10.11" | "11.4" | "11.8")
         "$MARIADB_BIN" \
             -h"$MARIADB_HOSTNAME" \
             -u"$MARIADB_SUPERUSER_USERNAME" \
@@ -1683,7 +1681,7 @@ function secureMariaDB {
             -e"FLUSH PRIVILEGES;" || abort "SQL statement failed"
         ;;
 
-    "sles15" | "opensuse15" | "debian11" | "ubuntu2004" | "ubuntu2204" | "ubuntu2404")
+    "sles15" | "opensuse15" | "debian11" | "debian12" | "debian13" | "ubuntu2004" | "ubuntu2204" | "ubuntu2404")
         log "Allow $MARIADB_SUPERUSER_USERNAME login only from localhost"
         "$MARIADB_BIN" \
             -h"$MARIADB_HOSTNAME" \
