Disable resetting PHP OpCache and rebuilding i-doit's own cache

diff --git a/idoit-jobs b/idoit-jobs
--- a/idoit-jobs
+++ b/idoit-jobs
@@ -35,10 +35,11 @@ CONFIGURATION_FILE="/etc/i-doit/i-doit.sh"
 function execute {
     local prefix=""
     local suffix="--user $IDOIT_USERNAME --password $IDOIT_PASSWORD --tenantId $TENANT_ID"
-    local randomString=""
-    randomString="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12)"
-    local phpFile="${INSTANCE_PATH}/${randomString}.php"
-    local statusCode=""
+## TODO See comments below:
+#    local randomString=""
+#    randomString="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12)"
+#    local phpFile="${INSTANCE_PATH}/${randomString}.php"
+#    local statusCode=""
 
     log "Perform important background tasks for i-doit"
 
@@ -67,26 +68,33 @@ function execute {
     eval "${prefix}${CONSOLE_BIN} notifications-send $suffix" || \
         abort "Command 'notifications-send' failed"
 
-    log "Clear PHP opcache"
-            cat << EOF | eval "${prefix}tee $phpFile" > /dev/null || \
-                abort "Unable to create file $phpFile"
-<?php
-
-if (function_exists('opcache_reset')) {
-    opcache_reset() or exit(1);
-}
-EOF
-    statusCode="$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' --url "http://localhost/${phpFile}")"
-    if [[ "$statusCode" != "200" ]]; then
-        abort "Unable to clear OpCache by HTTP request"
-    fi
-    eval "${prefix}rm $phpFile" || abort "Unable to remove file"
-
-    log "Re-cache by requesting i-doit Web GUI"
-    statusCode="$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' --url "http://localhost/")"
-    if [[ "$statusCode" != "200" ]]; then
-        abort "Unable to re-cache by HTTP request"
-    fi
+    ## TODO Clearing PHP OpCache is not working with i-doit >= 1.12 since PHP
+    ##      execution is restricted. In this case, request is redirected to
+    ##      /index.php.
+    ## TODO Additionally, "http" and "localhost" won't work on every
+    ##      environment.
+    ## TODO For both issues, there is no known working solution. Therefore,
+    ##      both jobs are disabled and will be removed in the near future.
+#    log "Clear PHP OpCache"
+#            cat << EOF | eval "${prefix}tee $phpFile" > /dev/null || \
+#                abort "Unable to create file $phpFile"
+#<?php
+#
+#if (function_exists('opcache_reset')) {
+#    opcache_reset() or exit(1);
+#}
+#EOF
+#    statusCode="$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' --url "http://localhost/${phpFile}")"
+#    if [[ "$statusCode" != "200" ]]; then
+#        abort "Unable to clear OpCache by HTTP request"
+#    fi
+#    eval "${prefix}rm $phpFile" || abort "Unable to remove file"
+#
+#    log "Re-cache by requesting i-doit Web GUI"
+#    statusCode="$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' --url "http://localhost/")"
+#    if [[ "$statusCode" != "200" ]]; then
+#        abort "Unable to re-cache by HTTP request"
+#    fi
 
     log "Clear caches"
     eval "${prefix}rm -rf ${INSTANCE_PATH}/temp/*" || \
