Increase Web server performance
- Switch from Apache module php to fcgid with php-fpm
- Switch from Apache module mpm_prefork to mpm_event
- Merge i-doit's .htaccess files into Apache site configuration

Debian GNU/Linux 9 only

diff --git a/idoit-install b/idoit-install
--- a/idoit-install
+++ b/idoit-install
@@ -485,9 +485,9 @@ function configureDebian9 {
 
     log "Install required Debian packages"
     apt-get -qq --yes install \
-        apache2 libapache2-mod-php \
+        apache2 libapache2-mod-fcgid \
         mariadb-client mariadb-server \
-        php php-bcmath php-cli php-common php-curl php-gd php-imagick php-json php-ldap \
+        php php-bcmath php-cli php-common php-curl php-fpm php-gd php-imagick php-json php-ldap \
         php-mbstring php-mcrypt php-memcached php-mysql php-pgsql php-soap php-xml php-zip \
         memcached unzip sudo moreutils || abort "Unable to install required Debian packages"
 }
@@ -799,6 +799,14 @@ EOF
         log "Enable PHP module for memcached"
         "$php_en_mod" memcached
     fi
+
+    case "$OS" in
+        "debian9")
+            log "Restart PHP process"
+            systemctl -q restart php7.0-fpm || abort \
+                "Unable to restart PHP process"
+            ;;
+    esac
 }
 
 function configureApache {
@@ -867,6 +875,112 @@ EOF
             log "Enable Apache module mod_access_compat"
             "$a2_en_mod" mod_access_compat || abort "Unable to enable Apache module mod_access_compat"
 
+            log "Restart Apache Web server"
+            systemctl -q restart apache2.service || abort "Unable to restart Apache Web server"
+            ;;
+        "debian9")
+            a2_en_site=$(command -v a2ensite)
+            a2_dis_site=$(command -v a2dissite)
+            a2_en_mod=$(command -v a2enmod)
+            a2_dis_mod=$(command -v a2dismod)
+
+            cat << EOF > /etc/apache2/sites-available/i-doit.conf || \
+                abort "Unable to create and edit file '/etc/apache2/sites-available/i-doit.conf'"
+<VirtualHost *:80>
+    ServerAdmin i-doit@example.net
+
+    DocumentRoot ${INSTALL_DIR}/
+    <Directory ${INSTALL_DIR}/>
+        AllowOverride None
+        Options -Indexes +FollowSymlinks
+        Require all granted
+
+        <IfModule mod_expires.c>
+            ExpiresActive On
+            ExpiresByType image/gif A2592000
+            ExpiresByType image/png A2592000
+            ExpiresByType image/jpg A2592000
+            ExpiresByType image/jpeg A2592000
+            ExpiresByType image/ico A2592000
+            ExpiresByType text/css A2592000
+            ExpiresByType text/javascript A2592000
+            ExpiresByType image/x-icon "access 1 year"
+            ExpiresDefault "access 2 week"
+            <IfModule mod_headers.c>
+                Header append Cache-Control "public"
+            </IfModule>
+        </IfModule>
+
+        <IfModule mod_rewrite.c>
+            RewriteEngine On
+
+            # security rules
+            RewriteRule .svn/ - [F]
+            RewriteRule ^controller$ - [F]
+            # Our code relies on the "controller.php" - See ID-5153
+            #RewriteRule ^controller\.php$ - [F]
+            RewriteRule ^console\.php$ - [F]
+            RewriteRule ^(INSTALL|UPDATE|checkmk_transfer.sh|idoit-rights.sh|vendor)$ - [F]
+
+            # favicon rewrite
+            RewriteRule favicon\.ico$ images/favicon.ico [L]
+
+            # base rewriting
+            RewriteCond %{REQUEST_FILENAME} !-l
+            RewriteCond %{REQUEST_FILENAME} !-f
+            RewriteCond %{REQUEST_FILENAME} !-d
+            RewriteRule .* index.php [L,QSA]
+        </IfModule>
+
+        <Files *.yml>
+            Require all denied
+        </Files>
+    </Directory>
+
+    <Directory ${INSTALL_DIR}/imports/>
+        <FilesMatch "\.(.*)$">
+            Require all denied
+        </FilesMatch>
+    </Directory>
+
+    <Directory ${INSTALL_DIR}/src/>
+        <Files ~ (.*?\.php)>
+            Require all denied
+        </Files>
+
+        <Files ~ (rt\.php|barcode_window\.php|barcode\.php|qr\.php|qr_img\.php|js\.php|jsonrpc\.php)>
+            Require all granted
+        </Files>
+    </Directory>
+
+    <FilesMatch \.php$>
+        SetHandler "proxy:unix:/var/run/php/php7.0-fpm.sock|fcgi://localhost"
+    </FilesMatch>
+
+    LogLevel warn
+    ErrorLog \${APACHE_LOG_DIR}/error.log
+    CustomLog \${APACHE_LOG_DIR}/access.log combined
+</VirtualHost>
+EOF
+
+            log "Disable default VHost"
+            "$a2_dis_site" 000-default || abort "Unable to disable default VHost"
+            log "Change directory ownership"
+            chown "$APACHE_USER":"$APACHE_GROUP" -R "${INSTALL_DIR}/" || \
+                abort "Unable to change ownership"
+            log "Enable new VHost settings"
+            "$a2_en_site" i-doit || abort "Unable to enable VHost settings"
+            log "Enable Apache module rewrite"
+            "$a2_en_mod" rewrite || abort "Unable to enable Apache module rewrite"
+            log "Enable Apache module alias"
+            "$a2_en_mod" alias || abort "Unable to enable Apache module alias"
+            log "Disable Apache module mpm_prefork"
+            "$a2_dis_mod" mpm_prefork || abort "Unable to enable Apache module mpm_prefork"
+            log "Enable Apache module mpm_event"
+            "$a2_en_mod" mpm_event || abort "Unable to enable Apache module mpm_event"
+            log "Let every user read the logs"
+            chmod 755 /var/log/apache2
+            chmod 664 /var/log/apache2/*
             log "Restart Apache Web server"
             systemctl -q restart apache2.service || abort "Unable to restart Apache Web server"
             ;;
