Eliminate issues found by ShellCheck
* Fix: Issues
* Add: Travis CI checks for all bash scripts

diff --git a/idoit-backup b/idoit-backup
--- a/idoit-backup
+++ b/idoit-backup
@@ -21,7 +21,8 @@
 ## along with this program. If not, see <http://www.gnu.org/licenses/>.
 ##
 
-set -u
+set -euo pipefail
+IFS=$'\n\t'
 
 ##
 ## Configuration
@@ -29,7 +30,7 @@ set -u
 
 USER="root"
 CONFIGURATION_FILE="/etc/i-doit/i-doit.sh"
-DATE=`date +%Y-%m-%d_%H-%M-%S`
+DATE=$(date +%Y-%m-%d_%H-%M-%S)
 
 ##--------------------------------------------------------------------------------------------------
 
@@ -52,7 +53,7 @@ function execute {
     log "Remove backups that are older than $BACKUP_AGE days"
 
     if [[ "$BACKUP_AGE" -ge 1 ]]; then
-        find "${BACKUP_DIR}"/* -mtime +${BACKUP_AGE} -exec rm {} \; || \
+        find "${BACKUP_DIR}"/* -mtime +"$BACKUP_AGE" -exec rm {} \; || \
             abort "Unable to remove out-dated backups"
     fi
 }
@@ -68,24 +69,25 @@ function dumpDatabase {
         gzip -9 > "${BACKUP_DIR}/${db_name}_${DATE}.sql.gz" || \
         abort "Unable to dump database"
 
-    rm -f ${BACKUP_DIR}/${db_name}_latest.sql.gz || abort "Unable to remove out-dated symlink"
+    rm -f "${BACKUP_DIR}/${db_name}_latest.sql.gz" || abort "Unable to remove out-dated symlink"
 
-    ln -s ${BACKUP_DIR}/${db_name}_${DATE}.sql.gz ${BACKUP_DIR}/${db_name}_latest.sql.gz || \
+    ln -s "${BACKUP_DIR}/${db_name}_${DATE}.sql.gz" "${BACKUP_DIR}/${db_name}_latest.sql.gz" || \
         abort "Unable to create symlink to latest dump"
 }
 
 function setup {
-    test `whoami` = "$USER" || abort "Only user '${USER}' may execute this script"
+    test "$(whoami)" = "$USER" || abort "Only user '${USER}' may execute this script"
 
     test -f "$CONFIGURATION_FILE" || abort "Missing configuration file '${CONFIGURATION_FILE}'"
 
+    # shellcheck source=/dev/null
     source "$CONFIGURATION_FILE" || abort "Unable to include configuration file"
 
     test -d "$INSTANCE_PATH" || abort "No i-doit instance found under '${INSTANCE_PATH}'"
 
     if [[ ! -d "$BACKUP_DIR" ]]; then
         log "Create backup directory '${BACKUP_DIR}'"
-        mkdir -p -m 775 "$BACKUP_DIR" || abort "Unable to create backup directory"
+        mkdir -p "$BACKUP_DIR" || abort "Unable to create backup directory"
     fi
 }
 
@@ -106,4 +108,6 @@ function abort {
 
 ##--------------------------------------------------------------------------------------------------
 
-setup && execute && finish
+if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
+    setup && execute && finish
+fi
diff --git a/idoit-jobs b/idoit-jobs
--- a/idoit-jobs
+++ b/idoit-jobs
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ##
-## i-doit cron jobs
+## i-doit jobs
 ##
 
 ##
@@ -21,7 +21,8 @@
 ## along with this program. If not, see <http://www.gnu.org/licenses/>.
 ##
 
-set -u
+set -euo pipefail
+IFS=$'\n\t'
 
 ##
 ## Configuration
@@ -34,41 +35,44 @@ CONFIGURATION_FILE="/etc/i-doit/i-doit.sh"
 function execute {
     local prefix=""
 
-    test `whoami` != "$APACHE_USER" && prefix="sudo -u $APACHE_USER "
+    test "$(whoami)" != "$APACHE_USER" && prefix="sudo -u $APACHE_USER "
 
     log "Clear caches"
-    ${prefix}rm -rf "$INSTANCE_PATH"/temp/* || abort "Unable to clear caches"
+    eval "${prefix}rm -rf ${INSTANCE_PATH}/temp/*" || abort "Unable to clear caches"
 
     log "Clear updates"
-    ${prefix}rm -rf "$INSTANCE_PATH"/updates/versions/* || abort "Unable to clear updates"
+    eval "${prefix}rm -rf ${INSTANCE_PATH}/updates/versions/*" || abort "Unable to clear updates"
 
     log "Archive i-doit logbook"
-    ${prefix}${CONTROLLER_BIN} archivelog || abort "Handler 'archivelog' failed"
+    eval "${prefix}${CONTROLLER_BIN} archivelog" || abort "Handler 'archivelog' failed"
     log ""
 
     log "Cleanup i-doit rights"
-    ${prefix}${CONTROLLER_BIN} cleanup_auth || abort "Handler 'cleanup_auth' failed"
+    eval "${prefix}${CONTROLLER_BIN} cleanup_auth" || abort "Handler 'cleanup_auth' failed"
     log ""
 
     log "Purge unfinished objects"
-    ${prefix}${CONTROLLER_BIN} cleanup_objects -t 1 || abort "Handler 'cleanup_objects' failed"
+    eval "${prefix}${CONTROLLER_BIN} cleanup_objects -t 1" || \
+        abort "Handler 'cleanup_objects' failed"
     log ""
 
     log "Truncate search index"
-    ${prefix}/usr/bin/mysql -u"$MARIADB_USERNAME" -p"$MARIADB_PASSWORD" \
-        -e"TRUNCATE TABLE ${TENANT_DATABASE}.isys_search_idx" || \
+    eval "${prefix}/usr/bin/mysql -u$MARIADB_USERNAME -p$MARIADB_PASSWORD \
+        -eTRUNCATE TABLE ${TENANT_DATABASE}.isys_search_idx" || \
         abort "Unable truncate search index"
 
     log "Re-create search index"
-    ${prefix}${CONTROLLER_BIN} search_index fullindex || abort "Handler 'search_index' failed"
+    eval "${prefix}${CONTROLLER_BIN} search_index fullindex" || \
+        abort "Handler 'search_index' failed"
 
     log "Send notifications"
-    ${prefix}${CONTROLLER_BIN} notifications || abort "Handler 'notifications' failed"
+    eval "${prefix}${CONTROLLER_BIN} notifications" || abort "Handler 'notifications' failed"
 }
 
 function setup {
     test -f "$CONFIGURATION_FILE" || abort "Missing configuration file '${CONFIGURATION_FILE}'"
 
+    # shellcheck source=/dev/null
     source "$CONFIGURATION_FILE" || abort "Unable to include configuration file"
 
     test -x "$CONTROLLER_BIN" || abort "Script '${CONTROLLER_BIN}' not found"
@@ -93,4 +97,6 @@ function abort {
 
 ##--------------------------------------------------------------------------------------------------
 
-setup && execute && finish
+if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
+    setup && execute && finish
+fi
diff --git a/idoit-restore b/idoit-restore
--- a/idoit-restore
+++ b/idoit-restore
@@ -21,7 +21,8 @@
 ## along with this program. If not, see <http://www.gnu.org/licenses/>.
 ##
 
-set -u
+set -euo pipefail
+IFS=$'\n\t'
 
 ##
 ## Configuration
@@ -29,7 +30,6 @@ set -u
 
 USER="root"
 CONFIGURATION_FILE="/etc/i-doit/i-doit.sh"
-DATE=`date +%Y-%m-%d_%H-%M-%S`
 
 ##--------------------------------------------------------------------------------------------------
 
@@ -38,7 +38,7 @@ function execute {
     restoreDatabase tenant "$TENANT_DATABASE"
 
     log "Restore i-doit instance located at '${INSTANCE_PATH}'"
-    rm -rf "$INSTANCE_PATH"/* || abort "Unable to clean up instance"
+    rm -rf "${INSTANCE_PATH:?}"/* || abort "Unable to clean up instance"
     tar xzf "${BACKUP_DIR}/i-doit_latest.tar.gz" -C / || abort "Unable to exstract files"
 }
 
@@ -58,10 +58,11 @@ function restoreDatabase {
 }
 
 function setup {
-    test `whoami` = "$USER" || abort "Only user '${USER}' may execute this script"
+    test "$(whoami)" = "$USER" || abort "Only user '${USER}' may execute this script"
 
     test -f "$CONFIGURATION_FILE" || abort "Missing configuration file '${CONFIGURATION_FILE}'"
 
+    # shellcheck source=/dev/null
     source "$CONFIGURATION_FILE" || abort "Unable to include configuration file"
 
     test -d "$INSTANCE_PATH" || abort "No i-doit instance found under '${INSTANCE_PATH}'"
@@ -88,11 +89,13 @@ function finish {
 }
 
 function abort {
-    echo -e "$1"  1>&2
+    echo -e "$1" 1>&2
     echo "Operation failed. Please check what is wrong and try again." 1>&2
     exit 1
 }
 
 ##--------------------------------------------------------------------------------------------------
 
-setup && execute && finish
+if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
+    setup && execute && finish
+fi
